[package]
name = "thin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

default = ['std']

alloc = ['init/alloc']
std = ['alloc', 'init/std']

[dependencies]
init = { path = '../init' }